name: new

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "select environment"
                required: true
                type: choice
                options:
                    - development
                    - staging
                    - production


jobs:
    try:
        runs-on: ubuntu-latest
        env:
            new: ${{ toJSON(github) }}
        steps:
            - run: echo " Hello World - ${{ env.new }}"
          